use_frameworks!

target 'SuperSaaSObjCSDK_Example' do
  pod 'SuperSaaSObjCSDK', :path => '../'

  target 'SuperSaaSObjCSDK_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end
